config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens
  root to: 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def new 
    @kitten = Kitten.new
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @kitten }
    end
  end

  def index 
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json {render json: @kittens }
    end
  end

  def create
    @kitten = Kitten.create(kitten_params)
    if @kitten.save 
      redirect_to kittens_path
      flash[:notice] = 'Kitten created successfully'
    else
      render :new
      flash[:notice] = 'Failed to create kitten'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)
    if @kitten.save
      redirect_to kittens_path
      flash[:notice] = "Kitten updated successfully"
    else
      redirect_to 'update'
      flash[:notice] = "Failed to update kitten"
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_path
    flash[:notice] = 'Kitten successfully destroyed'
  end

  private
    
  def kitten_params
    params.require(:kitten).permit(:name, :age, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div class="container" style="width: 60%">
  <h1 class="text-center text-primary my-2">Create a new Kitten!</h1>
  <%= form_for @kitten do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.number_field :age, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :softness %>
      <%= f.text_field :softness, class:"form-control" %>
    </div>
  
    <%= f.submit "Create", class:"text-center btn btn-primary px-4 py-2 mx-auto" %>
  <% end %>
</div>

app/views/kittens/edit.html.erb
<%= render 'form' %>
<%= link_to @kitten, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"} do %>
      <p class="btn btn-danger px-3 py-2 text-center card-text">Destroy</p>
<% end %>

app/views/kittens/index.html.erb
<h1 class="text-primary text-center mt-3">Kittens: </h1>

<%= link_to "Create new kitten", new_kitten_path, class: "btn btn-success px-3 py-2"%>


<hr class="my-3" />


<% @kittens.each do |kitten| %>

<div class='card mx-auto my-4' style="width:60%;">
  <div class="card-body">
    <h2 class="card-title text-primary mb-2">Name: <strong><%= link_to "#{kitten.name}", kitten %></strong></h3>
    <h3 class="card-subtitle text-muted">ID: <%= kitten.id %></h3>
    <h4 class="card-text text-primary mb-2">Age: <strong><%= kitten.age %></strong></h3>
    <h4 class="card-text text-primary">Softness: <strong><%= kitten.softness %></strong></h3>
    <%= link_to kitten, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"} do %>
      <p class="btn btn-danger px-3 py-2 text-center card-text">Destroy</p>
    <% end %>
    <%= link_to 'Edit', edit_kitten_path(kitten), class: "btn btn-warning px-3 py-2 text-center card-text"%>
  </div>
</div>
<% end %>

app/views/kittens/new.html.erb
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1 class="text-primary mt-2 text-center">Kitten <%= @kitten.id %></h1>

<hr class="my-3" />

<div class='card text-center'>
  <h3 class="text-primary mb-2 mt-3">Name: <strong><%= @kitten.name %></strong></h3>
  <h3 class="text-primary mb-2">Age: <strong><%= @kitten.age %></strong></h3>
  <h3 class="text-primary">Softness: <strong><%= @kitten.softness %></strong></h3>
  <p class="btn btn-warning mx-auto" style="width: 8%;"><%= link_to 'Edit', edit_kitten_path(@kitten) %></p>
  <%= link_to @kitten, method: :delete, data: {confirm: "Are you sure you want to delete this tweet?"} do %>
    <p class="btn btn-danger px-3 py-2 text-center card-text">Destroy</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info text-center">
        <h2><%= flash.notice %></h2>
      </div>
    <% end %>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>